### ISSUE TITLE
Add ability to filter the dashboard with categories, accounts and transaction type

### ISSUE THREAD

**Issue by nkuppan** [nkuppan/expensemanager#2]
Transaction Type
* Income
* Expense
* Transfer

Category: Can select multiple 

Accounts: Can select multiple

This will apply on top of the date filter

**Comment by Anshu-Bijarnia** [comment]
Can i try solving this? I am a beginner and would love to improve my skill solving this.

**Comment by nkuppan** [comment]
@Anshu-Bijarnia Appreciate that you are interested in the project. I am halfway to that specific work. Please keep an eye out and pickup something else.

**Comment by nkuppan** [comment]
Implemented this feature 

![image9](https://github.com/nkuppan/expensemanager/assets/9837639/49da6695-09a3-4ac2-b6f5-b36ad1b7af6a)
