### ISSUE TITLE
At first login, open the accounts page to onboard the user

### ISSUE THREAD

**Issue by jsramraj** [nkuppan/expensemanager#4]
When the user don't have any account at first, open up the accounts page and tell the user to add accounts and their current balacne to start with.
And then the Category page?

**Comment by nkuppan** [comment]
Hey @jsramraj, I have already added the onboarding screen to the project it's not been added to the flow. `OnboardingScreen`. I have to properly design the user workflow before adding them.

**Comment by nkuppan** [comment]
I am closing this since we have something to work on this. Not going to work soon.
