### ISSUE TITLE
Expense date selection getting wrong timezone

### ISSUE THREAD

**Issue by gabrielpbrollo** [nkuppan/expensemanager#8]
First, congrats for the app.

I am testing it in Brazil, when I select a date for my expense, it is actualy selecting a day before, maybe a timezone problem.

**Comment by nkuppan** [comment]
Hey @gabrielpbrollo, Thank you. I appreciate your using the app and reporting this issue. I am investigating it. Could you please explain this information such as what time zone, short video or screenshot?  It will be more helpful for me to resolve this quickly. Thank you :)

**Comment by gabrielpbrollo** [comment]
Sure, 
you can see in the video, I am selecting a date for my expense, and the value used by de app is a day before at 09:00 PM time, this is probably because the time zone. In the screenshot you can see that I am using -03:00 in Brazil.

It looks like the time zone in the calendar is not the same as the formatter that shows the selected value in the field.





![Screenshot_20240109-201723.png](https://github.com/nkuppan/expensemanager/assets/30435601/e1bdb59e-82d2-4463-b855-2360465e122c)

https://github.com/nkuppan/expensemanager/assets/30435601/bc7d5d81-b391-480b-b25a-fc25ae9f1b95

**Comment by nkuppan** [comment]
Hey @gabrielpbrollo, Appreciate your help. I have started to work on this issue and resolve this as quickly as possible.

**Comment by nkuppan** [comment]
Hey @gabrielpbrollo, I fixed this issue and updated the main branch. I validated this by switching the timezone on my mobile. It worked well. Thank you once again for reporting this. I appreciate your effort.

**Comment by gabrielpbrollo** [comment]
Awesome, thank you for providing such a good app and a very nice source code quality.
